// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package handler

import (
	"net/http"

	file "admin/internal/handler/file"
	role "admin/internal/handler/role"
	user "admin/internal/handler/user"
	"admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/file/download",
				Handler: file.Download(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: file.Upload(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/role/delete",
				Handler: role.Delete(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/role/edit",
				Handler: role.Edit(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/get",
				Handler: role.Get(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/role/list",
				Handler: role.List(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/add",
				Handler: user.Add(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/user/delete",
				Handler: user.Delete(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/list",
				Handler: user.List(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/user/modify",
				Handler: user.Modify(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
