// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type DeleteRoleRequest struct {
}

type DeleteRoleResponse struct {
}

type EditRoleRequest struct {
}

type EditRoleResponse struct {
}

type GetRoleRequest struct {
}

type GetRoleResponse struct {
}

type ListRoleRequest struct {
}

type ListRoleResponse struct {
}
