// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type OperateLogger struct {
	Uuid        string `json:"uuid"`
	Operator    string `json:"operator"` // 管理员账号
	Ipaddr      string `json:"ipaddr"`   // ip 地址
	Actions     string `json:"actions"`
	Contents    string `json:"contents"`
	Status      int    `json:"status"`
	CreateTime  int    `json:"createTime"`
	EventType   int    `json:"eventType"`
	EventLevel  int    `json:"eventLevel"`
	AuditStatus int    `json:"auditStatus"`
}
