// Code generated by jzero. DO NOT EDIT.
// type: clientset

package admin_go

import (
	"github.com/jzero-io/restc"
	"admin/admin-go/typed"

	"admin/admin-go/typed/admin"
)

type Interface interface {
	Direct() typed.DirectInterface

	Admin() admin.AdminInterface
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	admin *admin.AdminClient
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

func (x *Clientset) Admin() admin.AdminInterface {
	return x.admin
}

func NewClientWithOptions(ops ...restc.Opt) (admin.AdminInterface, error) {
	c := &restc.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.admin, err = admin.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	
	return cs.Admin(), nil
}