// Code generated by jzero. DO NOT EDIT.
// type: clientset

package gateway_go

import (
	"github.com/jzero-io/restc"
	"gateway/gateway-go/typed"

	"gateway/gateway-go/typed/gateway"
)

type Interface interface {
	Direct() typed.DirectInterface

	Gateway() gateway.GatewayInterface
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	gateway *gateway.GatewayClient
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

func (x *Clientset) Gateway() gateway.GatewayInterface {
	return x.gateway
}

func NewClientWithOptions(ops ...restc.Opt) (gateway.GatewayInterface, error) {
	c := &restc.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	cs.gateway, err = gateway.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	
	return cs.Gateway(), nil
}