// Code generated by jzero. DO NOT EDIT.
// type: admin_client

package admin

import (
	"github.com/jzero-io/restc"
)

type AdminInterface interface {
	RESTClient() restc.Interface
	
	FileGetter
	RoleGetter
	UserGetter
	
}

type AdminClient struct {
	restClient restc.Interface
}

func (x *AdminClient) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *AdminClient) File() FileInterface {
	return newFileClient(x)
}

func (x *AdminClient) Role() RoleInterface {
	return newRoleClient(x)
}

func (x *AdminClient) User() UserInterface {
	return newUserClient(x)
}


// NewForConfig creates a new AdminClient for the given config.
func NewForConfig(x *restc.RESTClient) (*AdminClient, error) {
	return &AdminClient{x}, nil
}