// Code generated by jzero. DO NOT EDIT.
// type: file

package admin

import (
	"admin/admin-go/model/admin/types"
	"context"

	"github.com/jzero-io/restc"
)

var (
	_ = context.Background()
)

type FileGetter interface {
	File() FileInterface
}

type FileInterface interface {
	// API /api/v1/file/download
	Download(param types.DownloadRequest) (*restc.Request, error)
	// API /api/v1/file/upload
	Upload() (*restc.Request, error)

	FileExpansion
}

type fileClient struct {
	client restc.Interface
}

func newFileClient(c *AdminClient) *fileClient {
	return &fileClient{
		client: c.RESTClient(),
	}
}

func (x *fileClient) Download(param types.DownloadRequest) (*restc.Request, error) {
	request := x.client.Verb("GET").
		SubPath(
			"/api/v1/file/download",
		)
	return request, nil
}

func (x *fileClient) Upload() (*restc.Request, error) {
	request := x.client.Verb("POST").
		SubPath(
			"/api/v1/file/upload",
		)
	return request, nil
}
