// Code generated by jzero. DO NOT EDIT.
// type: role

package admin

import (
	"admin/admin-go/model/admin/types"
	"context"

	"github.com/jzero-io/restc"
)

var (
	_ = context.Background()
)

type RoleGetter interface {
	Role() RoleInterface
}

type RoleInterface interface {
	// API /api/v1/role/delete
	Delete(ctx context.Context, param types.DeleteRoleRequest) (*types.DeleteRoleResponse, error)
	// API /api/v1/role/edit
	Edit(ctx context.Context, param types.EditRoleRequest) (*types.EditRoleResponse, error)
	// API /api/v1/role/get
	Get(ctx context.Context, param types.GetRoleRequest) (*types.GetRoleResponse, error)
	// API /api/v1/role/list
	List(ctx context.Context, param types.ListRoleRequest) (*types.ListRoleResponse, error)

	RoleExpansion
}

type roleClient struct {
	client restc.Interface
}

func newRoleClient(c *AdminClient) *roleClient {
	return &roleClient{
		client: c.RESTClient(),
	}
}

func (x *roleClient) Delete(ctx context.Context, param types.DeleteRoleRequest) (*types.DeleteRoleResponse, error) {
	var resp *types.DeleteRoleResponse
	err := x.client.Verb("GET").
		SubPath(
			"/api/v1/role/delete",
		).
		Params().
		Do(ctx).
		Into(&resp, true)

	if err != nil {
		return nil, err
	}

	return resp, nil
}

func (x *roleClient) Edit(ctx context.Context, param types.EditRoleRequest) (*types.EditRoleResponse, error) {
	var resp *types.EditRoleResponse
	err := x.client.Verb("POST").
		SubPath(
			"/api/v1/role/edit",
		).
		Params().
		Body(param).
		Do(ctx).
		Into(&resp, true)

	if err != nil {
		return nil, err
	}

	return resp, nil
}

func (x *roleClient) Get(ctx context.Context, param types.GetRoleRequest) (*types.GetRoleResponse, error) {
	var resp *types.GetRoleResponse
	err := x.client.Verb("GET").
		SubPath(
			"/api/v1/role/get",
		).
		Params().
		Do(ctx).
		Into(&resp, true)

	if err != nil {
		return nil, err
	}

	return resp, nil
}

func (x *roleClient) List(ctx context.Context, param types.ListRoleRequest) (*types.ListRoleResponse, error) {
	var resp *types.ListRoleResponse
	err := x.client.Verb("GET").
		SubPath(
			"/api/v1/role/list",
		).
		Params().
		Do(ctx).
		Into(&resp, true)

	if err != nil {
		return nil, err
	}

	return resp, nil
}
