// Code generated by jzero. DO NOT EDIT.
// type: gateway_client

package gateway

import (
	"github.com/jzero-io/restc"
)

type GatewayInterface interface {
	RESTClient() restc.Interface
	
	HelloGetter
	
}

type GatewayClient struct {
	restClient restc.Interface
}

func (x *GatewayClient) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

func (x *GatewayClient) Hello() HelloInterface {
	return newHelloClient(x)
}


// NewForConfig creates a new GatewayClient for the given config.
func NewForConfig(x *restc.RESTClient) (*GatewayClient, error) {
	return &GatewayClient{x}, nil
}