// Code generated by jzero. DO NOT EDIT.
package types

import (
    "time"
)

var (
    _ = time.Now()
)

type AddUserRequest struct {
	Name string `json:"name"`
}

type AddUserResponse struct {
	Status int `json:"status"`
}

type DeleteRoleRequest struct {
}

type DeleteRoleResponse struct {
}

type DeleteUserRequest struct {
	Id int `json:"id"`
}

type DeleteUserResponse struct {
	Status int `json:"status"`
}

type DownloadRequest struct {
	File_id string `form:"file_id"`
}

type EditRoleRequest struct {
}

type EditRoleResponse struct {
}

type GetRoleRequest struct {
}

type GetRoleResponse struct {
}

type ListRoleRequest struct {
}

type ListRoleResponse struct {
}

type ListUserRequest struct {
	Page int `form:"page"` // 第几页
	Size int `form:"size"` // 每页数量
}

type ListUserResponse struct {
	List []User `json:"list"`
	Total int `json:"total"`
}

type ModifyUserRequest struct {
	Id int `json:"id"`
	Name string `json:"name"`
}

type ModifyUserResponse struct {
	Status int `json:"status"`
}

type UploadResponse struct {
	Status int `json:"status"`
}

type User struct {
	Id int `json:"id"`
	Name string `json:"name"`
}